apiVersion: apps/v1
kind: Deployment
metadata:
  name: demandapi
  labels:
    app: demand-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: demandapi
  template:
    metadata:
      labels:
        app: demand-api
        service: demandapi
    spec:
      containers:
        - name: demandapi
          image: demandapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          
---
apiVersion: v1
kind: Service
metadata:
  name: demandapi
  labels:
    app: demand-api
    service: demandapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: demandapi