version: '3.8'

services:
  productapi:
    image: productapi
    ports:
      - 40000:80
    build:
      context: .
      dockerfile: product/Dockerfile

  administratorapi:
    image: administratorapi
    ports:
      - 40001:80
    build:
      context: .
      dockerfile: administrator/Dockerfile
      
  demandapi:
    image: demandapi
    ports:
      - 40002:80
    build:
      context: .
      dockerfile: demand/Dockerfile

